
[1m> Loading the world
Town10HD - RouteScenario_0
[1m> Running the route
Actor(id=500, type=sensor.camera.rgb)
0
/home/fhoekstra/CBS2/rails/models/ego_model.py:32: UserWarning: where received a uint8 condition tensor. This behavior is deprecated and will be removed in a future version of PyTorch. Use a boolean condition instead. (Triggered internally at ../aten/src/ATen/native/TensorCompare.cpp:413.)
  accel = torch.where(brake, self.brake_accel.expand(*brake.size()), self.throt_accel(throt))
/home/fhoekstra/miniconda3/envs/cbs2/lib/python3.7/site-packages/torch/nn/functional.py:4228: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  "Default grid_sample and affine_grid behavior has changed "
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
Shape of the first element in vizs: (400, 800, 3)
Video data shape: (3937, 3, 400, 800)
Logged video with name: vid_whqhqtdtpp.mp4
Saving to dataset/small_800-400_R07_10HD/tqpiojxaoi
[91mStopping the route, the agent has crashed:
[91m> Collector has collided!! Heading out :P
[1m> Stopping the route
[1m========= Results of RouteScenario_0 (repetition 0) ------ [91mFAILURE[39m[22m [1m=========
╒═════════════════════════════════╤═════════════════════╕
│ Start Time                      │ 2024-06-24 21:43:01 │
├─────────────────────────────────┼─────────────────────┤
│ End Time                        │ 2024-06-24 21:52:34 │
├─────────────────────────────────┼─────────────────────┤
│ Duration (System Time)          │ 572.85s             │
├─────────────────────────────────┼─────────────────────┤
│ Duration (Game Time)            │ 196.85s             │
├─────────────────────────────────┼─────────────────────┤
│ Ratio (System Time / Game Time) │ 0.344               │
╘═════════════════════════════════╧═════════════════════╛
╒═══════════════════════╤═════════╤═════════╕
│ Criterion             │ Result  │ Value   │
├───────────────────────┼─────────┼─────────┤
│ RouteCompletionTest   │ [91mFAILURE[39m │ 28.7 %  │
├───────────────────────┼─────────┼─────────┤
│ OutsideRouteLanesTest │ [92mSUCCESS[39m │ 0 %     │
├───────────────────────┼─────────┼─────────┤
│ CollisionTest         │ [91mFAILURE[39m │ 1 times │
├───────────────────────┼─────────┼─────────┤
│ RunningRedLightTest   │ [92mSUCCESS[39m │ 0 times │
├───────────────────────┼─────────┼─────────┤
│ RunningStopTest       │ [92mSUCCESS[39m │ 0 times │
├───────────────────────┼─────────┼─────────┤
│ InRouteTest           │ [92mSUCCESS[39m │         │
├───────────────────────┼─────────┼─────────┤
│ AgentBlockedTest      │ [92mSUCCESS[39m │         │
├───────────────────────┼─────────┼─────────┤
│ Timeout               │ [92mSUCCESS[39m │         │
╘═══════════════════════╧═════════╧═════════╛
[1m> Registering the route statistics
[1m========= Preparing RouteScenario_0 (repetition 1) =========
[1m> Setting up the agent
[1m> Loading the world
Traceback (most recent call last):
  File "/home/fhoekstra/CBS2/leaderboard/leaderboard/scenarios/scenario_manager.py", line 152, in _tick_scenario
    ego_action = self._agent()
  File "/home/fhoekstra/CBS2/leaderboard/leaderboard/autoagents/agent_wrapper.py", line 88, in __call__
    return self._agent()
  File "/home/fhoekstra/CBS2/leaderboard/leaderboard/autoagents/autonomous_agent.py", line 115, in __call__
    control = self.run_step(input_data, timestamp)
  File "autoagents/collector_agents/collector.py", line 402, in run_step
    raise Exception('Collector has collided!! Heading out :P')
Exception: Collector has collided!! Heading out :P
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/fhoekstra/CBS2/leaderboard/leaderboard/leaderboard_evaluator.py", line 368, in _load_and_run_scenario
    self.manager.run_scenario()
  File "/home/fhoekstra/CBS2/leaderboard/leaderboard/scenarios/scenario_manager.py", line 136, in run_scenario
    self._tick_scenario(timestamp)
  File "/home/fhoekstra/CBS2/leaderboard/leaderboard/scenarios/scenario_manager.py", line 159, in _tick_scenario
    raise AgentError(e)
leaderboard.autoagents.agent_wrapper.AgentError: Collector has collided!! Heading out :P
Town10HD - RouteScenario_0
[1m> Running the route
Actor(id=905, type=sensor.camera.rgb)
0
WARNING:py.warnings:/home/fhoekstra/miniconda3/envs/cbs2/lib/python3.7/site-packages/torch/nn/functional.py:4228: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  "Default grid_sample and affine_grid behavior has changed "
100
200
300
400
500
600
700
Shape of the first element in vizs: (400, 800, 3)
Video data shape: (771, 3, 400, 800)
Logged video with name: vid_xthbvmyqta.mp4
Saving to dataset/small_800-400_R07_10HD/fhsxgrwyqz
[91mStopping the route, the agent has crashed:
[91m> Collector has collided!! Heading out :P
[1m> Stopping the route
[1m========= Results of RouteScenario_0 (repetition 1) ------ [91mFAILURE[39m[22m [1m=========
╒═════════════════════════════════╤═════════════════════╕
│ Start Time                      │ 2024-06-24 21:52:38 │
├─────────────────────────────────┼─────────────────────┤
│ End Time                        │ 2024-06-24 21:54:52 │
├─────────────────────────────────┼─────────────────────┤
│ Duration (System Time)          │ 134.28s             │
├─────────────────────────────────┼─────────────────────┤
│ Duration (Game Time)            │ 38.55s              │
├─────────────────────────────────┼─────────────────────┤
│ Ratio (System Time / Game Time) │ 0.287               │
╘═════════════════════════════════╧═════════════════════╛
╒═══════════════════════╤═════════╤═════════╕
│ Criterion             │ Result  │ Value   │
├───────────────────────┼─────────┼─────────┤
│ RouteCompletionTest   │ [91mFAILURE[39m │ 12.61 % │
├───────────────────────┼─────────┼─────────┤
│ OutsideRouteLanesTest │ [92mSUCCESS[39m │ 0 %     │
├───────────────────────┼─────────┼─────────┤
│ CollisionTest         │ [91mFAILURE[39m │ 1 times │
├───────────────────────┼─────────┼─────────┤
│ RunningRedLightTest   │ [92mSUCCESS[39m │ 0 times │
├───────────────────────┼─────────┼─────────┤
│ RunningStopTest       │ [92mSUCCESS[39m │ 0 times │
├───────────────────────┼─────────┼─────────┤
│ InRouteTest           │ [92mSUCCESS[39m │         │
├───────────────────────┼─────────┼─────────┤
│ AgentBlockedTest      │ [92mSUCCESS[39m │         │
├───────────────────────┼─────────┼─────────┤
│ Timeout               │ [92mSUCCESS[39m │         │
╘═══════════════════════╧═════════╧═════════╛
[1m> Registering the route statistics
[1m========= Preparing RouteScenario_0 (repetition 2) =========
[1m> Setting up the agent
[1m> Loading the world
Traceback (most recent call last):
  File "/home/fhoekstra/CBS2/leaderboard/leaderboard/scenarios/scenario_manager.py", line 152, in _tick_scenario
    ego_action = self._agent()
  File "/home/fhoekstra/CBS2/leaderboard/leaderboard/autoagents/agent_wrapper.py", line 88, in __call__
    return self._agent()
  File "/home/fhoekstra/CBS2/leaderboard/leaderboard/autoagents/autonomous_agent.py", line 115, in __call__
    control = self.run_step(input_data, timestamp)
  File "autoagents/collector_agents/collector.py", line 402, in run_step
    raise Exception('Collector has collided!! Heading out :P')
Exception: Collector has collided!! Heading out :P
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/fhoekstra/CBS2/leaderboard/leaderboard/leaderboard_evaluator.py", line 368, in _load_and_run_scenario
    self.manager.run_scenario()
  File "/home/fhoekstra/CBS2/leaderboard/leaderboard/scenarios/scenario_manager.py", line 136, in run_scenario
    self._tick_scenario(timestamp)
  File "/home/fhoekstra/CBS2/leaderboard/leaderboard/scenarios/scenario_manager.py", line 159, in _tick_scenario
    raise AgentError(e)
leaderboard.autoagents.agent_wrapper.AgentError: Collector has collided!! Heading out :P
Town10HD - RouteScenario_0
[1m> Running the route
Actor(id=1303, type=sensor.camera.rgb)
0
100
200
